//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_SurveyQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rb_SurveyQuestions()
        {
            this.rb_SurveyAnswers = new HashSet<rb_SurveyAnswers>();
            this.rb_SurveyBeaconQuestions = new HashSet<rb_SurveyBeaconQuestions>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<bool> FreeFormComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_SurveyAnswers> rb_SurveyAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rb_SurveyBeaconQuestions> rb_SurveyBeaconQuestions { get; set; }
    }
}
