//using ApplicationGeneration.Models;
//using iTextSharp.text.pdf;
//using System.IO;

//namespace ApplicaitonGeneration.Helpers
//{
//    public static partial class Document
//    {
//        static public byte[] Generate322West57LeaseApplicationCount(string inputDir, RealtorClient clientinfo)
//        {

//            var inputFile = inputDir + "322West57LeaseApplication.pdf";
//            var reader = new iTextSharp.text.pdf.PdfReader(inputFile);
//            var stream = new MemoryStream();
//            var stamper = new PdfStamper(reader, stream);

//            var fields = stamper.AcroFields;
//            fields.SetField("Building Name", "#1");
//            fields.SetField("Sell", "#2");
//            fields.SetField("Lease", "#3");
//            fields.SetField("Applicant Names", "#4");
//            fields.SetField("Purchase Price", "#5");
//            fields.SetField("Proposed Closing Date", "#6");
//            fields.SetField("Anticipated Occupancy Date", "#7");
//            fields.SetField("Current CoOwner Name", "#8");
//            fields.SetField("Owner Date", "#9");
//            fields.SetField("CoOwn Date", "#10");
//            fields.SetField("Unit #", "#11");
//            fields.SetField("Building Address", "#12");
//            fields.SetField("Monthly Rental", "#13");
//            fields.SetField("Annual Rent", "#14");
//            fields.SetField("Security Deposit", "#15");
//            fields.SetField("Lease Term", "#16");
//            fields.SetField("Lease Start Date", "#17");
//            fields.SetField("Lease End Date", "#18");
//            fields.SetField("Current Owner Name", "#19");
//            fields.SetField("Current Owner Address 1", "#20");
//            fields.SetField("Current Owner Address 2", "#21");
//            fields.SetField("Current Owner Home Phone", "#22");
//            fields.SetField("Applicant Home Phone", "#23");
//            fields.SetField("Applicant Address 1", "#24");
//            fields.SetField("Applicant Address 2", "#25");
//            fields.SetField("App from", "#26");
//            fields.SetField("App To", "#27");
//            fields.SetField("LandlordAgent 1", "#28");
//            fields.SetField("LandlordAgent Address", "#29");
//            fields.SetField("CoApp Home Phone", "#30");
//            fields.SetField("CoApp Current Address", "#31");
//            fields.SetField("CoApp Current Address 2", "#32");
//            fields.SetField("CoApp Date from", "#33");
//            fields.SetField("Applicant Housing", "#34");
//            fields.SetField("CoApp Date to", "#35");
//            fields.SetField("CoApp Housing", "#36");
//            fields.SetField("CoApp Landlord Agent", "#37");
//            fields.SetField("CoApp Landlord Agent Address", "#38");
//            fields.SetField("FT", "#39");
//            fields.SetField("PT", "#40");
//            fields.SetField("SE", "#41");
//            fields.SetField("RET", "#42");
//            fields.SetField("ST", "#43");
//            fields.SetField("UN", "#44");
//            fields.SetField("Applicant Profession", "#45");
//            fields.SetField("App Emp Date", "#46");
//            fields.SetField("App Emp End", "#47");
//            fields.SetField("Supervisors Name", "#48");
//            fields.SetField("Supervisors Phone", "#49");
//            fields.SetField("Annual Base Salary", "#50");
//            fields.SetField("App Prior Employer", "#51");
//            fields.SetField("App Prior Empl Address", "#52");
//            fields.SetField("App Prior Empl Address 2", "#53");
//            fields.SetField("App prior Emp", "#54");
//            fields.SetField("App Prior emp end", "#55");
//            fields.SetField("ft", "#56");
//            fields.SetField("pt", "#57");
//            fields.SetField("se", "#58");
//            fields.SetField("ret", "#59");
//            fields.SetField("st", "#60");
//            fields.SetField("un", "#61");
//            fields.SetField("CoApp profession", "#62");
//            fields.SetField("Co App Employer", "#63");
//            fields.SetField("CoApp Empl Addess", "#64");
//            fields.SetField("CoApp Emp Date", "#65");
//            fields.SetField("CoApp Emp End", "#66");
//            fields.SetField("CoApp Supervisor Name", "#67");
//            fields.SetField("CoApp Supervisor Phone", "#68");
//            fields.SetField("CoApp Prior Empl", "#69");
//            fields.SetField("CoApp Prior Emp Address", "#70");
//            fields.SetField("CoApp Prior Emp Address 2", "#71");
//            fields.SetField("CoApp Pr Emp Date", "#72");
//            fields.SetField("CoApp prior emp end", "#73");
//            fields.SetField("App Date", "#74");
//            fields.SetField("Applicant Last Name", "#75");
//            fields.SetField("App Prior Supervisors Name", "#76");
//            fields.SetField("App Prior Supervisors Phone", "#77");
//            fields.SetField("Education History", "#78");
//            fields.SetField("CoApp Prior Supervisor Name", "#79");
//            fields.SetField("CoApp Prior Suprevisor Phone", "#80");
//            fields.SetField("CoApp Education History", "#81");
//            fields.SetField("App Bank 1 Name", "#82");
//            fields.SetField("App Bank 1 Address", "#83");
//            fields.SetField("ck1", "#84");
//            fields.SetField("sv1", "#85");
//            fields.SetField("ln1", "#86");
//            fields.SetField("App Bank 2 Name", "#87");
//            fields.SetField("App Bank 2 Address", "#88");
//            fields.SetField("ck2", "#89");
//            fields.SetField("sv2", "#90");
//            fields.SetField("ln2", "#91");
//            fields.SetField("App Bank 3 Name", "#92");
//            fields.SetField("App Bank 3 Address", "#93");
//            fields.SetField("ck3", "#94");
//            fields.SetField("sv3", "#95");
//            fields.SetField("ln3", "#96");
//            fields.SetField("App Stockborker CPA Name", "#97");
//            fields.SetField("App Stockbroker CPA Firm", "#98");
//            fields.SetField("App Stockbroker CPA Address", "#99");
//            fields.SetField("App Stockbroker CPA Phone", "#100");
//            fields.SetField("App Stockbroker CPA Email", "#101");
//            fields.SetField("CoApp Bank 1 Name", "#102");
//            fields.SetField("CoApp Bank 1 Address", "#103");
//            fields.SetField("ck4", "#104");
//            fields.SetField("sv4", "#105");
//            fields.SetField("ln4", "#106");
//            fields.SetField("CoApp Bank 2 Name", "#107");
//            fields.SetField("CoApp Bank 2 Address", "#108");
//            fields.SetField("ck5", "#109");
//            fields.SetField("sv5", "#110");
//            fields.SetField("ln5", "#111");
//            fields.SetField("CoApp Bank 3 Name", "#112");
//            fields.SetField("CoApp Bank 3 Address", "#113");
//            fields.SetField("ck6", "#114");
//            fields.SetField("sv6", "#115");
//            fields.SetField("ln6", "#116");
//            fields.SetField("CoApp Stockbroker CPA Name", "#117");
//            fields.SetField("CoApp Stockbroker CPA Firm", "#118");
//            fields.SetField("CoApp Stockbroker CPA Address", "#119");
//            fields.SetField("CoApp Stockbroker CPA Phone", "#120");
//            fields.SetField("CoApp Stockbroker CPA EMail", "#121");
//            fields.SetField("App Personal Ref 1", "#122");
//            fields.SetField("App Personal Ref 1 Phone", "#123");
//            fields.SetField("App Personal Ref 1 Email", "#124");
//            fields.SetField("App Personal Ref 2", "#125");
//            fields.SetField("App Personal Ref 2 Phone", "#126");
//            fields.SetField("App Personal Ref 2 Email", "#127");
//            fields.SetField("App Personal Ref 3", "#128");
//            fields.SetField("App Personal Ref 3 Phone", "#129");
//            fields.SetField("App Personal Ref 3 Email", "#130");
//            fields.SetField("CoApp Personal Ref 1", "#131");
//            fields.SetField("CoApp Personal REf 1 Phone", "#132");
//            fields.SetField("CoApp Personal Ref 1 Email", "#133");
//            fields.SetField("CoApp Personal Ref 2", "#134");
//            fields.SetField("CoApp Personal Ref 2 Phone", "#135");
//            fields.SetField("CoApp Personal REf 2 Email", "#136");
//            fields.SetField("CoApp Personal REf 3", "#137");
//            fields.SetField("CoApp Personal Ref 3 Phone", "#138");
//            fields.SetField("CoApp Personal REf 3 Email", "#139");
//            fields.SetField("App Prof Ref 1", "#140");
//            fields.SetField("App Prof Ref 1 Phone", "#141");
//            fields.SetField("App Prof Ref 1 Email", "#142");
//            fields.SetField("App Prof Ref 2", "#143");
//            fields.SetField("App Prof Ref 2 Phone", "#144");
//            fields.SetField("App Prof Ref 2 Email", "#145");
//            fields.SetField("CoApp Prof Ref 1", "#146");
//            fields.SetField("CoApp Prof Ref 1 Phone", "#147");
//            fields.SetField("CoApp Prof Ref 1 Email", "#148");
//            fields.SetField("CoApp Prof Ref 2", "#149");
//            fields.SetField("CoApp Prof Ref 2 Phone", "#150");
//            fields.SetField("CoApp Prof Ref 2 Email", "#151");
//            fields.SetField("App Prof Ref 3", "#152");
//            fields.SetField("App Prof Ref 3 Phone", "#153");
//            fields.SetField("App Prof Ref 3 Email", "#154");
//            fields.SetField("CoApp Prof Ref 3", "#155");
//            fields.SetField("CoApp Prof Ref 3 Phone", "#156");
//            fields.SetField("CoApp Prof Ref 3 Email", "#157");
//            fields.SetField("NA", "#158");
//            fields.SetField("Relation to Applicant", "#159");
//            fields.SetField("Guarantor Phone", "#160");
//            fields.SetField("Guar Bank Name 1", "#161");
//            fields.SetField("Guar Bank 1 Address", "#162");
//            fields.SetField("GrCk", "#163");
//            fields.SetField("GRSV", "#164");
//            fields.SetField("GRLN", "#165");
//            fields.SetField("Guar Bank 2 Name", "#166");
//            fields.SetField("Guar Bank 2 Address", "#167");
//            fields.SetField("grck", "#168");
//            fields.SetField("grsv", "#169");
//            fields.SetField("grln", "#170");
//            fields.SetField("Gr ft", "#171");
//            fields.SetField("Gr pt", "#172");
//            fields.SetField("Gr se", "#173");
//            fields.SetField("Gr R", "#174");
//            fields.SetField("GR st", "#175");
//            fields.SetField("Gr Un", "#176");
//            fields.SetField("Guar Profession", "#177");
//            fields.SetField("Guar Employer", "#178");
//            fields.SetField("Guar Empl Address 1", "#179");
//            fields.SetField("Guar Empl Address 2", "#180");
//            fields.SetField("Guar Emp Date", "#181");
//            fields.SetField("Guar Emp To", "#182");
//            fields.SetField("Guar Supervisor Name", "#183");
//            fields.SetField("Guar Supervisor Phone", "#184");
//            fields.SetField("Guar Base Salary", "#185");
//            fields.SetField("Residents Known", "#186");
//            fields.SetField("Residents Known 2", "#187");
//            fields.SetField("YES", "#188");
//            fields.SetField("NO", "#189");
//            fields.SetField("If yes list type breed and age", "#190");
//            fields.SetField("Y", "#191");
//            fields.SetField("N", "#192");
//            fields.SetField("Full", "#193");
//            fields.SetField("PArt", "#194");
//            fields.SetField("Pied", "#195");
//            fields.SetField("Applicant Name", "#196");
//            fields.SetField("Applicant Address1", "#197");
//            fields.SetField("Applicant Address2", "#198");
//            fields.SetField("CoApp Name", "#199");
//            fields.SetField("CoApp Address1", "#200");
//            fields.SetField("CoApp Address2", "#201");
//            fields.SetField("App Cash", "#202");
//            fields.SetField("App MMF", "#203");
//            fields.SetField("App contract Deposit", "#204");
//            fields.SetField("App Investments", "#205");
//            fields.SetField("App Invest Own Biz", "#206");
//            fields.SetField("App Acct Rec", "#207");
//            fields.SetField("App RE owned", "#208");
//            fields.SetField("Year1", "#209");
//            fields.SetField("Make1", "#210");
//            fields.SetField("App Car1", "#211");
//            fields.SetField("App Car 2", "#212");
//            fields.SetField("App Pers Ppty", "#213");
//            fields.SetField("App Life Ins", "#214");
//            fields.SetField("App Retire Funds", "#215");
//            fields.SetField("App 401K", "#216");
//            fields.SetField("App KEOGH", "#217");
//            fields.SetField("App Profit Sharing Pension Plan", "#218");
//            fields.SetField("App Other Assets Schedule D", "#219");
//            fields.SetField("App TOTAL ASSETS", "#220");
//            fields.SetField("CoApp Cash", "#221");
//            fields.SetField("CoApp MMF", "#222");
//            fields.SetField("CoApp Contract Dep", "#223");
//            fields.SetField("CoApp Investment", "#224");
//            fields.SetField("CoApp Invest Own Biz", "#225");
//            fields.SetField("CoApp Acct Rec", "#226");
//            fields.SetField("CoApp RE Owned", "#227");
//            fields.SetField("Year2", "#228");
//            fields.SetField("Make2", "#229");
//            fields.SetField("CoApp Car1", "#230");
//            fields.SetField("CoApp Car2", "#231");
//            fields.SetField("CoApp Pers Ppty", "#232");
//            fields.SetField("CoApp Life Ins", "#233");
//            fields.SetField("CoApp Retire Fund", "#234");
//            fields.SetField("CoApp 401K", "#235");
//            fields.SetField("CoApp KEOGH", "#236");
//            fields.SetField("CoApp Profit Sharing Pension Plan", "#237");
//            fields.SetField("CoApp Other Assets Schedule D", "#238");
//            fields.SetField("CoApp TOTAL ASSETS", "#239");
//            fields.SetField("COMBINED ASSETS", "#240");
//            fields.SetField("App Base Salary", "#241");
//            fields.SetField("App Overtime Wages", "#242");
//            fields.SetField("App Bonus and Commissions", "#243");
//            fields.SetField("App Dividends and Interest Income", "#244");
//            fields.SetField("App Real Estate Income Net", "#245");
//            fields.SetField("App Schedule H Other Income Including Gifts", "#246");
//            fields.SetField("App Source of Income Total", "#247");
//            fields.SetField("CoApp Base Salary", "#248");
//            fields.SetField("CoApp Overtime Wages", "#249");
//            fields.SetField("CoApp Bonus and Commissions", "#250");
//            fields.SetField("CoApp Dividends and Interest Income", "#251");
//            fields.SetField("CoApp Real Estate Income Net", "#252");
//            fields.SetField("CoApp Schedule H Other Income Including Gifts", "#253");
//            fields.SetField("CoApp Source of Income", "#254");
//            fields.SetField("Personal Bank Accounts at", "#255");
//            fields.SetField("Savings and Loan Accounts at", "#256");
//            fields.SetField("Purpose of Loan", "#257");
//            fields.SetField("coPersonal Bank Accounts at", "#258");
//            fields.SetField("coSavings and Loan Accounts at", "#259");
//            fields.SetField("coPurpose of Loan", "#260");
//            fields.SetField("Notes Payable Schedule E", "#261");
//            fields.SetField("To Banks", "#262");
//            fields.SetField("To Relatives", "#263");
//            fields.SetField("To Others", "#264");
//            fields.SetField("Installment Accounts Payable", "#265");
//            fields.SetField("Automobile", "#266");
//            fields.SetField("Other", "#267");
//            fields.SetField("Other Accounts Payable", "#268");
//            fields.SetField("Schedule F Mortgages Payable on Real Estate", "#269");
//            fields.SetField("Unpaid Real Estate Taxes", "#270");
//            fields.SetField("Unpaid Income Taxes", "#271");
//            fields.SetField("Chattel Mortgages", "#272");
//            fields.SetField("Loans on Life Insurance Policies Include Premium Advances", "#273");
//            fields.SetField("Outstanding Credit Card Debt", "#274");
//            fields.SetField("Other Debts Schedule G", "#275");
//            fields.SetField("TOTAL LIABILITIES", "#276");
//            fields.SetField("NET WORTH", "#277");
//            fields.SetField("coNotes Payable Schedule E", "#278");
//            fields.SetField("coTo Banks", "#279");
//            fields.SetField("coTo Relatives", "#280");
//            fields.SetField("coTo Others", "#281");
//            fields.SetField("coInstallment Accounts Payable", "#282");
//            fields.SetField("coAutomobile", "#283");
//            fields.SetField("coOther", "#284");
//            fields.SetField("coOther Accounts Payable", "#285");
//            fields.SetField("coSchedule F Mortgages Payable on Real Estate", "#286");
//            fields.SetField("coUnpaid Real Estate Taxes", "#287");
//            fields.SetField("coUnpaid Income Taxes", "#288");
//            fields.SetField("coChattel Mortgages", "#289");
//            fields.SetField("coLoans on Life Insurance Policies Include Premium Advances", "#290");
//            fields.SetField("coOutstanding Credit Card Debt", "#291");
//            fields.SetField("coOther Debts Schedule G", "#292");
//            fields.SetField("coTOTAL LIABILITIES", "#293");
//            fields.SetField("coNET WORTH", "#294");
//            fields.SetField("COMBINED LIABILITIES", "#295");
//            fields.SetField("Maintenance", "#296");
//            fields.SetField("Apartment Financing", "#297");
//            fields.SetField("Other Mortgages", "#298");
//            fields.SetField("Bank Loans", "#299");
//            fields.SetField("Auto Loans", "#300");
//            fields.SetField("Other_2", "#301");
//            fields.SetField("TOTAL", "#302");
//            fields.SetField("coMaintenance", "#303");
//            fields.SetField("coApartment Financing", "#304");
//            fields.SetField("coOther Mortgages", "#305");
//            fields.SetField("coBank Loans", "#306");
//            fields.SetField("coAuto Loans", "#307");
//            fields.SetField("coOther_2", "#308");
//            fields.SetField("coTOTAL", "#309");
//            fields.SetField("coCOMBINED TOTAL", "#310");
//            fields.SetField("An Endorser or Comaker on Notes", "#311");
//            fields.SetField("Alimony Payments Annual", "#312");
//            fields.SetField("Child Support", "#313");
//            fields.SetField("Legal Action", "#314");
//            fields.SetField("Judgments", "#315");
//            fields.SetField("Bankruptcy", "#316");
//            fields.SetField("Have you ever taken bankruptcy Explain", "#317");
//            fields.SetField("Have you ever taken bankruptcy Explain2", "#318");
//            fields.SetField("Have you ever taken bankruptcy Explain3", "#319");
//            fields.SetField("Applicant or CoApplicantRow1", "#320");
//            fields.SetField("Financial InstitutionRow1", "#321");
//            fields.SetField("Type of AccountRow1", "#322");
//            fields.SetField("Account BalanceRow1", "#323");
//            fields.SetField("Applicant or CoApplicantRow2", "#324");
//            fields.SetField("Financial InstitutionRow2", "#325");
//            fields.SetField("Type of AccountRow2", "#326");
//            fields.SetField("Account BalanceRow2", "#327");
//            fields.SetField("Applicant or CoApplicantRow3", "#328");
//            fields.SetField("Financial InstitutionRow3", "#329");
//            fields.SetField("Type of AccountRow3", "#330");
//            fields.SetField("Account BalanceRow3", "#331");
//            fields.SetField("Applicant or CoApplicantRow4", "#332");
//            fields.SetField("Financial InstitutionRow4", "#333");
//            fields.SetField("Type of AccountRow4", "#334");
//            fields.SetField("Account BalanceRow4", "#335");
//            fields.SetField("Applicant or CoApplicantRow5", "#336");
//            fields.SetField("Financial InstitutionRow5", "#337");
//            fields.SetField("Type of AccountRow5", "#338");
//            fields.SetField("Account BalanceRow5", "#339");
//            fields.SetField("Amount No of SharesRow1", "#340");
//            fields.SetField("DescriptionRow1", "#341");
//            fields.SetField("Marketable ValueRow1", "#342");
//            fields.SetField("NonMarketable ValueRow1", "#343");
//            fields.SetField("Amount No of SharesRow2", "#344");
//            fields.SetField("DescriptionRow2", "#345");
//            fields.SetField("Marketable ValueRow2", "#346");
//            fields.SetField("NonMarketable ValueRow2", "#347");
//            fields.SetField("Amount No of SharesRow3", "#348");
//            fields.SetField("DescriptionRow3", "#349");
//            fields.SetField("Marketable ValueRow3", "#350");
//            fields.SetField("NonMarketable ValueRow3", "#351");
//            fields.SetField("Amount No of SharesRow4", "#352");
//            fields.SetField("DescriptionRow4", "#353");
//            fields.SetField("Marketable ValueRow4", "#354");
//            fields.SetField("NonMarketable ValueRow4", "#355");
//            fields.SetField("Amount No of SharesRow5", "#356");
//            fields.SetField("DescriptionRow5", "#357");
//            fields.SetField("Marketable ValueRow5", "#358");
//            fields.SetField("NonMarketable ValueRow5", "#359");
//            fields.SetField("Description and LocationRow1", "#360");
//            fields.SetField("Date AcquiredRow1", "#361");
//            fields.SetField("CostRow1", "#362");
//            fields.SetField("Actual ValueRow1", "#363");
//            fields.SetField("Mortgage AmountRow1", "#364");
//            fields.SetField("Maturity DateRow1", "#365");
//            fields.SetField("Monthly Operating CostsRow1", "#366");
//            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow1", "#367");
//            fields.SetField("Description and LocationRow2", "#368");
//            fields.SetField("Date AcquiredRow2", "#369");
//            fields.SetField("CostRow2", "#370");
//            fields.SetField("Actual ValueRow2", "#371");
//            fields.SetField("Mortgage AmountRow2", "#372");
//            fields.SetField("Maturity DateRow2", "#373");
//            fields.SetField("Monthly Operating CostsRow2", "#374");
//            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow2", "#375");
//            fields.SetField("Description and LocationRow3", "#376");
//            fields.SetField("Date AcquiredRow3", "#377");
//            fields.SetField("CostRow3", "#378");
//            fields.SetField("Actual ValueRow3", "#379");
//            fields.SetField("Mortgage AmountRow3", "#380");
//            fields.SetField("Maturity DateRow3", "#381");
//            fields.SetField("Monthly Operating CostsRow3", "#382");
//            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow3", "#383");
//            fields.SetField("Description and LocationRow4", "#384");
//            fields.SetField("Date AcquiredRow4", "#385");
//            fields.SetField("CostRow4", "#386");
//            fields.SetField("Actual ValueRow4", "#387");
//            fields.SetField("Mortgage AmountRow4", "#388");
//            fields.SetField("Maturity DateRow4", "#389");
//            fields.SetField("Monthly Operating CostsRow4", "#390");
//            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow4", "#391");
//            fields.SetField("Description and LocationRow5", "#392");
//            fields.SetField("Date AcquiredRow5", "#393");
//            fields.SetField("CostRow5", "#394");
//            fields.SetField("Actual ValueRow5", "#395");
//            fields.SetField("Mortgage AmountRow5", "#396");
//            fields.SetField("Maturity DateRow5", "#397");
//            fields.SetField("Monthly Operating CostsRow5", "#398");
//            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow5", "#399");
//            fields.SetField("DescriptionRow1_2", "#400");
//            fields.SetField("AmountRow1", "#401");
//            fields.SetField("DescriptionRow2_2", "#402");
//            fields.SetField("AmountRow2", "#403");
//            fields.SetField("DescriptionRow3_2", "#404");
//            fields.SetField("AmountRow3", "#405");
//            fields.SetField("DescriptionRow4_2", "#406");
//            fields.SetField("AmountRow4", "#407");
//            fields.SetField("To Whom PayableRow1", "#408");
//            fields.SetField("DateRow1", "#409");
//            fields.SetField("AmountRow1_2", "#410");
//            fields.SetField("DueRow1", "#411");
//            fields.SetField("InterestRow1", "#412");
//            fields.SetField("Pledged as SecurityRow1", "#413");
//            fields.SetField("To Whom PayableRow2", "#414");
//            fields.SetField("DateRow2", "#415");
//            fields.SetField("AmountRow2_2", "#416");
//            fields.SetField("DueRow2", "#417");
//            fields.SetField("InterestRow2", "#418");
//            fields.SetField("Pledged as SecurityRow2", "#419");
//            fields.SetField("To Whom PayableRow3", "#420");
//            fields.SetField("DateRow3", "#421");
//            fields.SetField("AmountRow3_2", "#422");
//            fields.SetField("DueRow3", "#423");
//            fields.SetField("InterestRow3", "#424");
//            fields.SetField("Pledged as SecurityRow3", "#425");
//            fields.SetField("To Whom PayableRow4", "#426");
//            fields.SetField("DateRow4", "#427");
//            fields.SetField("AmountRow4_2", "#428");
//            fields.SetField("DueRow4", "#429");
//            fields.SetField("InterestRow4", "#430");
//            fields.SetField("Pledged as SecurityRow4", "#431");
//            fields.SetField("To Whom PayableRow1_2", "#432");
//            fields.SetField("Mortgage AmountRow1_2", "#433");
//            fields.SetField("Principal RemainingRow1", "#434");
//            fields.SetField("Maturity DateRow1_2", "#435");
//            fields.SetField("To Whom PayableRow2_2", "#436");
//            fields.SetField("Mortgage AmountRow2_2", "#437");
//            fields.SetField("Principal RemainingRow2", "#438");
//            fields.SetField("Maturity DateRow2_2", "#439");
//            fields.SetField("To Whom PayableRow3_2", "#440");
//            fields.SetField("Mortgage AmountRow3_2", "#441");
//            fields.SetField("Principal RemainingRow3", "#442");
//            fields.SetField("Maturity DateRow3_2", "#443");
//            fields.SetField("To Whom PayableRow4_2", "#444");
//            fields.SetField("Mortgage AmountRow4_2", "#445");
//            fields.SetField("Principal RemainingRow4", "#446");
//            fields.SetField("Maturity DateRow4_2", "#447");
//            fields.SetField("DescriptionRow1_3", "#448");
//            fields.SetField("AmountRow1_3", "#449");
//            fields.SetField("DateRow1_2", "#450");
//            fields.SetField("PaymentsRow1", "#451");
//            fields.SetField("SecurityRow1", "#452");
//            fields.SetField("DescriptionRow2_3", "#453");
//            fields.SetField("AmountRow2_3", "#454");
//            fields.SetField("DateRow2_2", "#455");
//            fields.SetField("PaymentsRow2", "#456");
//            fields.SetField("SecurityRow2", "#457");
//            fields.SetField("DescriptionRow3_3", "#458");
//            fields.SetField("AmountRow3_3", "#459");
//            fields.SetField("DateRow3_2", "#460");
//            fields.SetField("PaymentsRow3", "#461");
//            fields.SetField("SecurityRow3", "#462");
//            fields.SetField("DescriptionRow4_3", "#463");
//            fields.SetField("AmountRow4_3", "#464");
//            fields.SetField("DateRow4_2", "#465");
//            fields.SetField("PaymentsRow4", "#466");
//            fields.SetField("SecurityRow4", "#467");
//            fields.SetField("SourceRow1", "#468");
//            fields.SetField("Amount Last YearRow1", "#469");
//            fields.SetField("Is this recurringRow1", "#470");
//            fields.SetField("SourceRow2", "#471");
//            fields.SetField("Amount Last YearRow2", "#472");
//            fields.SetField("Is this recurringRow2", "#473");
//            fields.SetField("SourceRow3", "#474");
//            fields.SetField("Amount Last YearRow3", "#475");
//            fields.SetField("Is this recurringRow3", "#476");
//            fields.SetField("SourceRow4", "#477");
//            fields.SetField("Amount Last YearRow4", "#478");
//            fields.SetField("Is this recurringRow4", "#479");
//            fields.SetField("DividendApp1", "#480");
//            fields.SetField("DividendCo1", "#481");
//            fields.SetField("DividendApp2", "#482");
//            fields.SetField("DividendCo2", "#483");
//            fields.SetField("DividendApp3", "#484");
//            fields.SetField("DividendCo3", "#485");
//            fields.SetField("Day", "#486");
//            fields.SetField("Month", "#487");
//            fields.SetField("Year", "#488");
//            fields.SetField("CoApp Date", "#489");
//            fields.SetField("App DOB", "#490");
//            fields.SetField("App SSN", "#491");
//            fields.SetField("Applicant Address", "#492");
//            fields.SetField("Applicant City", "#493");
//            fields.SetField("Applicant State", "#494");
//            fields.SetField("Applicant Zip", "#495");
//            fields.SetField("CoApp DOB", "#496");
//            fields.SetField("CoApp SSN", "#497");
//            fields.SetField("CoApp Address", "#498");
//            fields.SetField("CoApp City", "#499");
//            fields.SetField("CoApp State", "#500");
//            fields.SetField("CoApp Zip", "#501");
//            fields.SetField("Other Adult Name", "#502");
//            fields.SetField("Other DOB", "#503");
//            fields.SetField("Other SSN", "#504");
//            fields.SetField("Other Address", "#505");
//            fields.SetField("Other City", "#506");
//            fields.SetField("Other State", "#507");
//            fields.SetField("Other Zip", "#508");
//            fields.SetField("Fowarding Address 1", "#509");
//            fields.SetField("Forwarding Address 2", "#510");
//            fields.SetField("Onwer Biz Address 1", "#511");
//            fields.SetField("Owner Biz Address 2", "#512");
//            fields.SetField("Unit Owner Day Phone", "#513");
//            fields.SetField("Unit Owner Eve Phone", "#514");
//            fields.SetField("Unit Owner Cell Phone", "#515");
//            fields.SetField("Unit Owner Email", "#516");
//            fields.SetField("Applicant Email", "#517");
//            fields.SetField("Applicant Employer", "#518");
//            fields.SetField("Applicant Business Email", "#519");
//            fields.SetField("Applicant Empl Address", "#520");
//            fields.SetField("Applicant Cell Phone", "#521");
//            fields.SetField("Applicant Empl Address 2", "#522");
//            fields.SetField("Applicant Work Phone", "#523");
//            fields.SetField("Other Contact Information", "#524");
//            fields.SetField("CoApp Email", "#525");
//            fields.SetField("CoApp Employer", "#526");
//            fields.SetField("CoApp Business Email", "#527");
//            fields.SetField("CoApp Empl Address", "#528");
//            fields.SetField("CoApp Cell Phone", "#529");
//            fields.SetField("CoApp Empl Address 2", "#530");
//            fields.SetField("CoApp Work Phone", "#531");
//            fields.SetField("CoApp Other Contact Information", "#532");
//            fields.SetField("Emergency Contact", "#533");
//            fields.SetField("Relationship", "#534");
//            fields.SetField("Emergency Email", "#535");
//            fields.SetField("Emergency Contact Home Phone", "#536");
//            fields.SetField("Emergency contact Cell Phone", "#537");
//            fields.SetField("Additional Occupant 1", "#538");
//            fields.SetField("Age 1", "#539");
//            fields.SetField("Relationship 1", "#540");
//            fields.SetField("Additional Occupant 2", "#541");
//            fields.SetField("Age 2", "#542");
//            fields.SetField("Relationship 2", "#543");
//            fields.SetField("Additional Occupant 3", "#544");
//            fields.SetField("Age 3", "#545");
//            fields.SetField("Relationship 3", "#546");
//            fields.SetField("Additional Occupant 4", "#547");
//            fields.SetField("Age 4", "#548");
//            fields.SetField("Relationship 4", "#549");
//            fields.SetField("Additional Occupant 5", "#550");
//            fields.SetField("Age 5", "#551");
//            fields.SetField("Relationship 5", "#552");
//            fields.SetField("Other Date", "#553");
//            fields.SetField("Guarantor Name", "#554");
//            fields.SetField("Guarantor Date", "#555");
//            fields.SetField("Gurantor Date", "#556");
//            fields.SetField("Check Box6", "#557");
//            fields.SetField("Check Box7", "#558");
//            fields.SetField("Check Box8", "#559");
//            fields.SetField("Check Box9", "#560");
//            fields.SetField("Check Box10", "#561");
//            fields.SetField("Check Box11", "#562");
//            fields.SetField("Check Box12", "#563");
//            fields.SetField("Text26", "#564");
//            fields.SetField("Text28", "#565");
//            fields.SetField("Text29", "#566");
//            fields.SetField("Text30", "#567");
//            fields.SetField("Name of Corporation 1", "#568");
//            fields.SetField("Name of Corporation 2", "#569");
//            fields.SetField("Occupant 1", "#570");
//            fields.SetField("Occupant 3", "#571");
//            fields.SetField("Occupant 5", "#572");
//            fields.SetField("Occupant 7", "#573");
//            fields.SetField("Occupant 2", "#574");
//            fields.SetField("Occupant 4", "#575");
//            fields.SetField("Occupant 6", "#576");
//            fields.SetField("Occupant 8", "#577");
//            fields.SetField("Term of Occupancy", "#578");
//            fields.SetField("Relationship to Corporation", "#579");
//            fields.SetField("Name  Title of Authorized Officer", "#580");
//            fields.SetField("Date_19", "#581");
//            fields.SetField("existence or nonexistence of a Sprinkler System in the Leased Premises 1", "#582");
//            fields.SetField("existence or nonexistence of a Sprinkler System in the Leased Premises 2", "#583");
//            fields.SetField("1", "#584");
//            fields.SetField("2", "#585");
//            fields.SetField("the Leased", "#586");
//            fields.SetField("undefined", "#587");
//            fields.SetField("inspected was on", "#588");
//            fields.SetField("Acknowledgment  Signatures", "#589");
//            fields.SetField("New York State Real Property Law Article 7 Section 231a 1", "#590");
//            fields.SetField("New York State Real Property Law Article 7 Section 231a 2", "#591");
//            fields.SetField("1_2", "#592");
//            fields.SetField("2_2", "#593");
//            fields.SetField("1_3", "#594");
//            fields.SetField("2_3", "#595");
//            fields.SetField("Date", "#596");
//            fields.SetField("Date_2", "#597");
//            fields.SetField("Date_3", "#598");
//            fields.SetField("Check Box1", "#599");
//            fields.SetField("Check Box2", "#600");

//            stamper.FormFlattening = true;
//            stamper.Dispose();
//            var result = stream.ToArray();

//            reader.Close();

//            return result;
//        }
//    }
//}
