using ApplicationGeneration.Models;
using iTextSharp.text.pdf;
using System;
using System.IO;

namespace ApplicaitonGeneration.Helpers
{
    public static partial class RealtorDocument
    {
        static public byte[] Generate322West57LeaseApplication(string inputDir, RealtorClient applicant, RealtorClient coapplicant)
        {

            var inputFile = inputDir + "322West57LeaseApplication.pdf";
            var reader = new iTextSharp.text.pdf.PdfReader(inputFile);
            var stream = new MemoryStream();
            var stamper = new PdfStamper(reader, stream);

            var fields = stamper.AcroFields;
            fields.SetField("Building Name", "The Sheffield");
            //if (applicant.clienttype == 1)
            //    fields.SetField("Sell", "Yes");
            //else
            //    fields.SetField("Lease", "No");
            fields.SetField("Applicant Names", applicant.ContactInfo.FirstName + " " + applicant.ContactInfo.LastName);
            fields.SetField("Purchase Price", "");
            fields.SetField("Proposed Closing Date", "");
            fields.SetField("Anticipated Occupancy Date", "");
            fields.SetField("Current CoOwner Name", "");
            fields.SetField("Owner Date", DateTime.Now.ToString().Split(' ')[0]);
            fields.SetField("CoOwn Date", DateTime.Now.ToString().Split(' ')[0]);
            fields.SetField("Unit #", "");
            fields.SetField("Building Address", "322 West 57th street");
            fields.SetField("Monthly Rental", "");
            fields.SetField("Annual Rent", "");
            fields.SetField("Security Deposit", "");
            fields.SetField("Lease Term", "");
            fields.SetField("Lease Start Date", "");
            fields.SetField("Lease End Date", "");
            fields.SetField("Current Owner Name", "");
            fields.SetField("Current Owner Address 1", "");
            fields.SetField("Current Owner Address 2", "");
            fields.SetField("Current Owner Home Phone", "");
            fields.SetField("Applicant Home Phone", applicant.ContactInfo.PhoneNumber);
            fields.SetField("Applicant Address 1", applicant.ApartmentCurrent.Address.AddressLine1);
            fields.SetField("Applicant Address 2", applicant.ApartmentCurrent.Address.AddressLine2);
            fields.SetField("App from", applicant.ApartmentCurrent.Lease.Timespan.StartDate);
            fields.SetField("App To", applicant.ApartmentCurrent.Lease.Timespan.EndDate);
            //fields.SetField("LandlordAgent 1", applicant.ApartmentCurrent.Landlord.ContactInfo.FullName);
            //fields.SetField("LandlordAgent Address", applicant.ApartmentCurrent.Landlord.AddressFull);
            fields.SetField("CoApp Home Phone", coapplicant.ContactInfo.PhoneNumber);
            fields.SetField("CoApp Current Address", coapplicant.ApartmentCurrent.Address.AddressLine1);
            fields.SetField("CoApp Current Address 2", coapplicant.ApartmentCurrent.Address.AddressLine2);
            fields.SetField("CoApp Date from", coapplicant.ApartmentCurrent.Lease.Timespan.EndDate);
            fields.SetField("Applicant Housing", "");
            fields.SetField("CoApp Date to", coapplicant.ApartmentCurrent.Lease.Timespan.EndDate);
            fields.SetField("CoApp Housing", "");
            //fields.SetField("CoApp Landlord Agent", coapplicant.ApartmentCurrent.Landlord.ContactInfo.FullName);
            //fields.SetField("CoApp Landlord Agent Address", coapplicant.ApartmentCurrent.Landlord.AddressFull);
            fields.SetField("FT", "1");
            fields.SetField("PT", "2");
            fields.SetField("SE", "Yes");
            fields.SetField("RET", "No");
            fields.SetField("ST", "Y");
            fields.SetField("UN", "N");
            fields.SetField("Applicant Profession", applicant.EmploymentCurrent.Occupation.Occupation);
            fields.SetField("App Emp Date", applicant.EmploymentCurrent.Occupation.Timespan.StartDate);
            fields.SetField("App Emp End", applicant.EmploymentCurrent.Occupation.Timespan.EndDate);
            fields.SetField("Supervisors Name", applicant.EmploymentCurrent.Supervisor.ContactInfo.FullName);
            fields.SetField("Supervisors Phone", applicant.EmploymentCurrent.Supervisor.ContactInfo.PhoneNumber);
            fields.SetField("Annual Base Salary", applicant.EmploymentCurrent.Salary.AnnualSalary);
            fields.SetField("App Prior Employer", applicant.EmploymentPrevious.Occupation.Occupation);
            fields.SetField("App Prior Empl Address", applicant.EmploymentPrevious.Address.AddressLine1);
            fields.SetField("App Prior Empl Address 2", applicant.EmploymentPrevious.Address.AddressLine2);
            fields.SetField("App prior Emp", applicant.EmploymentPrevious.Occupation.Timespan.StartDate);
            fields.SetField("App Prior emp end", applicant.EmploymentPrevious.Occupation.Timespan.EndDate);
            fields.SetField("ft", "1");
            fields.SetField("pt", "NO");
            fields.SetField("se", "No");
            fields.SetField("ret", "Yes");
            fields.SetField("st", "YES");
            fields.SetField("un", "");
            fields.SetField("CoApp profession", coapplicant.EmploymentCurrent.Occupation.Occupation);
            fields.SetField("Co App Employer", coapplicant.EmploymentCurrent.Occupation.CompanyName);
            fields.SetField("CoApp Empl Addess", coapplicant.EmploymentCurrent.Address.AddressLine1);
            fields.SetField("CoApp Emp Date", applicant.EmploymentCurrent.Occupation.Timespan.StartDate);
            fields.SetField("CoApp Emp End", applicant.EmploymentCurrent.Occupation.Timespan.EndDate);
            fields.SetField("CoApp Supervisor Name", coapplicant.EmploymentCurrent.Supervisor.ContactInfo.FullName);
            fields.SetField("CoApp Supervisor Phone", coapplicant.EmploymentCurrent.Supervisor.ContactInfo.PhoneNumber);
            fields.SetField("CoApp Prior Empl", coapplicant.EmploymentPrevious.Occupation.Occupation);
            fields.SetField("CoApp Prior Emp Address", coapplicant.EmploymentPrevious.Address.AddressLine1);
            fields.SetField("CoApp Prior Emp Address 2", coapplicant.EmploymentPrevious.Address.AddressLine2);
            fields.SetField("CoApp Pr Emp Date", "");
            fields.SetField("CoApp prior emp end", "");
            fields.SetField("App Date", DateTime.Now.ToString().Split(' ')[0]);
            fields.SetField("Applicant Last Name", applicant.ContactInfo.LastName);
            fields.SetField("App Prior Supervisors Name", applicant.EmploymentPrevious.Supervisor.ContactInfo.FullName);
            fields.SetField("App Prior Supervisors Phone", applicant.EmploymentPrevious.Supervisor.ContactInfo.PhoneNumber);
            fields.SetField("Education History", "");
            fields.SetField("CoApp Prior Supervisor Name", coapplicant.EmploymentPrevious.Supervisor.ContactInfo.FullName);
            fields.SetField("CoApp Prior Suprevisor Phone", coapplicant.EmploymentPrevious.Supervisor.ContactInfo.PhoneNumber);
            fields.SetField("CoApp Education History", "");
            //fields.SetField("App Bank 1 Name", applicant.bank1.bankname);
            //fields.SetField("App Bank 1 Address", applicant.bank1.bankaddress);
            //fields.SetField("ck1", applicant.bank1.checking.ToString());
            //fields.SetField("sv1", applicant.bank1.savings.ToString());
            //fields.SetField("ln1", applicant.bank1.loan.ToString());
            //fields.SetField("App Bank 2 Name", applicant.bank2.bankname);
            //fields.SetField("App Bank 2 Address", applicant.bank2.bankaddress);
            //fields.SetField("ck2", applicant.bank2.checking.ToString());
            //fields.SetField("sv2", applicant.bank2.savings.ToString());
            //fields.SetField("ln2", applicant.bank2.loan.ToString());
            //fields.SetField("App Bank 3 Name", applicant.bank3.bankname);
            //fields.SetField("App Bank 3 Address", applicant.bank3.bankaddress);
            //fields.SetField("ck3", applicant.bank3.checking.ToString());
            //fields.SetField("sv3", applicant.bank3.savings.ToString());
            //fields.SetField("ln3", applicant.bank3.loan.ToString());
            fields.SetField("App Stockborker CPA Name", "");
            fields.SetField("App Stockbroker CPA Firm", "");
            fields.SetField("App Stockbroker CPA Address", "");
            fields.SetField("App Stockbroker CPA Phone", "");
            fields.SetField("App Stockbroker CPA Email", "");
            //fields.SetField("CoApp Bank 1 Name", coapplicant.bank1.bankname);
            //fields.SetField("CoApp Bank 1 Address", coapplicant.bank2.bankaddress);
            fields.SetField("ck4", "");
            fields.SetField("sv4", "");
            fields.SetField("ln4", "");
            //fields.SetField("CoApp Bank 2 Name", coapplicant.bank2.bankname);
            //fields.SetField("CoApp Bank 2 Address", coapplicant.bank2.bankaddress);
            fields.SetField("ck5", "");
            fields.SetField("sv5", "");
            fields.SetField("ln5", "");
            //fields.SetField("CoApp Bank 3 Name", coapplicant.bank3.bankname);
            //fields.SetField("CoApp Bank 3 Address", coapplicant.bank3.bankaddress);
            fields.SetField("ck6", "");
            fields.SetField("sv6", "");
            fields.SetField("ln6", "");
            fields.SetField("CoApp Stockbroker CPA Name", "");
            fields.SetField("CoApp Stockbroker CPA Firm", "");
            fields.SetField("CoApp Stockbroker CPA Address", "");
            fields.SetField("CoApp Stockbroker CPA Phone", "");
            fields.SetField("CoApp Stockbroker CPA EMail", "");
            fields.SetField("App Personal Ref 1", "");
            fields.SetField("App Personal Ref 1 Phone", "");
            fields.SetField("App Personal Ref 1 Email", "");
            fields.SetField("App Personal Ref 2", "");
            fields.SetField("App Personal Ref 2 Phone", "");
            fields.SetField("App Personal Ref 2 Email", "");
            fields.SetField("App Personal Ref 3", "");
            fields.SetField("App Personal Ref 3 Phone", "");
            fields.SetField("App Personal Ref 3 Email", "");
            fields.SetField("CoApp Personal Ref 1", "");
            fields.SetField("CoApp Personal REf 1 Phone", "");
            fields.SetField("CoApp Personal Ref 1 Email", "");
            fields.SetField("CoApp Personal Ref 2", "");
            fields.SetField("CoApp Personal Ref 2 Phone", "");
            fields.SetField("CoApp Personal REf 2 Email", "");
            fields.SetField("CoApp Personal REf 3", "");
            fields.SetField("CoApp Personal Ref 3 Phone", "");
            fields.SetField("CoApp Personal REf 3 Email", "");
            fields.SetField("App Prof Ref 1", "");
            fields.SetField("App Prof Ref 1 Phone", "");
            fields.SetField("App Prof Ref 1 Email", "");
            fields.SetField("App Prof Ref 2", "");
            fields.SetField("App Prof Ref 2 Phone", "");
            fields.SetField("App Prof Ref 2 Email", "");
            fields.SetField("CoApp Prof Ref 1", "");
            fields.SetField("CoApp Prof Ref 1 Phone", "");
            fields.SetField("CoApp Prof Ref 1 Email", "");
            fields.SetField("CoApp Prof Ref 2", "");
            fields.SetField("CoApp Prof Ref 2 Phone", "");
            fields.SetField("CoApp Prof Ref 2 Email", "");
            fields.SetField("App Prof Ref 3", "");
            fields.SetField("App Prof Ref 3 Phone", "");
            fields.SetField("App Prof Ref 3 Email", "");
            fields.SetField("CoApp Prof Ref 3", "");
            fields.SetField("CoApp Prof Ref 3 Phone", "");
            fields.SetField("CoApp Prof Ref 3 Email", "");
            fields.SetField("NA", "");
            fields.SetField("Relation to Applicant", "");
            fields.SetField("Guarantor Phone", "");
            fields.SetField("Guar Bank Name 1", "");
            fields.SetField("Guar Bank 1 Address", "");
            fields.SetField("GrCk", "");
            fields.SetField("GRSV", "");
            fields.SetField("GRLN", "");
            fields.SetField("Guar Bank 2 Name", "");
            fields.SetField("Guar Bank 2 Address", "");
            fields.SetField("grck", "");
            fields.SetField("grsv", "");
            fields.SetField("grln", "");
            fields.SetField("Gr ft", "");
            fields.SetField("Gr pt", "");
            fields.SetField("Gr se", "");
            fields.SetField("Gr R", "");
            fields.SetField("GR st", "");
            fields.SetField("Gr Un", "");
            fields.SetField("Guar Profession", "");
            fields.SetField("Guar Employer", "");
            fields.SetField("Guar Empl Address 1", "");
            fields.SetField("Guar Empl Address 2", "");
            fields.SetField("Guar Emp Date", "");
            fields.SetField("Guar Emp To", "");
            fields.SetField("Guar Supervisor Name", "");
            fields.SetField("Guar Supervisor Phone", "");
            fields.SetField("Guar Base Salary", "");
            fields.SetField("Residents Known", "");
            fields.SetField("Residents Known 2", "");
            fields.SetField("YES", "");
            fields.SetField("NO", "");
            fields.SetField("If yes list type breed and age", "");
            fields.SetField("Y", "");
            fields.SetField("N", "");
            fields.SetField("Full", "");
            fields.SetField("PArt", "");
            fields.SetField("Pied", "");
            fields.SetField("Applicant Name", applicant.ContactInfo.FirstName + " " + applicant.ContactInfo.LastName);
            fields.SetField("Applicant Address1", applicant.ApartmentCurrent.Address.AddressLine1);
            fields.SetField("Applicant Address2", applicant.ApartmentCurrent.Address.AddressLine2);
            fields.SetField("CoApp Name", "");
            fields.SetField("CoApp Address1", "");
            fields.SetField("CoApp Address2", "");
            fields.SetField("App Cash", "");
            fields.SetField("App MMF", "");
            fields.SetField("App contract Deposit", "");
            fields.SetField("App Investments", "");
            fields.SetField("App Invest Own Biz", "");
            fields.SetField("App Acct Rec", "");
            fields.SetField("App RE owned", "");
            fields.SetField("Year1", "");
            fields.SetField("Make1", "");
            fields.SetField("App Car1", "");
            fields.SetField("App Car 2", "");
            fields.SetField("App Pers Ppty", "");
            fields.SetField("App Life Ins", "");
            fields.SetField("App Retire Funds", "");
            fields.SetField("App 401K", "");
            fields.SetField("App KEOGH", "");
            fields.SetField("App Profit Sharing Pension Plan", "");
            fields.SetField("App Other Assets Schedule D", "");
            fields.SetField("App TOTAL ASSETS", "");
            fields.SetField("CoApp Cash", "");
            fields.SetField("CoApp MMF", "");
            fields.SetField("CoApp Contract Dep", "");
            fields.SetField("CoApp Investment", "");
            fields.SetField("CoApp Invest Own Biz", "");
            fields.SetField("CoApp Acct Rec", "");
            fields.SetField("CoApp RE Owned", "");
            fields.SetField("Year2", "");
            fields.SetField("Make2", "");
            fields.SetField("CoApp Car1", "");
            fields.SetField("CoApp Car2", "");
            fields.SetField("CoApp Pers Ppty", "");
            fields.SetField("CoApp Life Ins", "");
            fields.SetField("CoApp Retire Fund", "");
            fields.SetField("CoApp 401K", "");
            fields.SetField("CoApp KEOGH", "");
            fields.SetField("CoApp Profit Sharing Pension Plan", "");
            fields.SetField("CoApp Other Assets Schedule D", "");
            fields.SetField("CoApp TOTAL ASSETS", "");
            fields.SetField("COMBINED ASSETS", "");
            fields.SetField("App Base Salary", applicant.EmploymentCurrent.Salary.AnnualSalary);
            fields.SetField("App Overtime Wages", "");
            fields.SetField("App Bonus and Commissions", applicant.EmploymentCurrent.Salary.Bonus);
            fields.SetField("App Dividends and Interest Income", "");
            fields.SetField("App Real Estate Income Net", "");
            fields.SetField("App Schedule H Other Income Including Gifts", "");
            fields.SetField("App Source of Income Total", "");
            fields.SetField("CoApp Base Salary", "");
            fields.SetField("CoApp Overtime Wages", "");
            fields.SetField("CoApp Bonus and Commissions", "");
            fields.SetField("CoApp Dividends and Interest Income", "");
            fields.SetField("CoApp Real Estate Income Net", "");
            fields.SetField("CoApp Schedule H Other Income Including Gifts", "");
            fields.SetField("CoApp Source of Income", "");
            fields.SetField("Personal Bank Accounts at", "");
            fields.SetField("Savings and Loan Accounts at", "");
            fields.SetField("Purpose of Loan", "");
            fields.SetField("coPersonal Bank Accounts at", "");
            fields.SetField("coSavings and Loan Accounts at", "");
            fields.SetField("coPurpose of Loan", "");
            fields.SetField("Notes Payable Schedule E", "");
            fields.SetField("To Banks", "");
            fields.SetField("To Relatives", "");
            fields.SetField("To Others", "");
            fields.SetField("Installment Accounts Payable", "");
            fields.SetField("Automobile", "");
            fields.SetField("Other", "");
            fields.SetField("Other Accounts Payable", "");
            fields.SetField("Schedule F Mortgages Payable on Real Estate", "");
            fields.SetField("Unpaid Real Estate Taxes", "");
            fields.SetField("Unpaid Income Taxes", "");
            fields.SetField("Chattel Mortgages", "");
            fields.SetField("Loans on Life Insurance Policies Include Premium Advances", "");
            fields.SetField("Outstanding Credit Card Debt", "");
            fields.SetField("Other Debts Schedule G", "");
            fields.SetField("TOTAL LIABILITIES", "");
            fields.SetField("NET WORTH", "");
            fields.SetField("coNotes Payable Schedule E", "");
            fields.SetField("coTo Banks", "");
            fields.SetField("coTo Relatives", "");
            fields.SetField("coTo Others", "");
            fields.SetField("coInstallment Accounts Payable", "");
            fields.SetField("coAutomobile", "");
            fields.SetField("coOther", "");
            fields.SetField("coOther Accounts Payable", "");
            fields.SetField("coSchedule F Mortgages Payable on Real Estate", "");
            fields.SetField("coUnpaid Real Estate Taxes", "");
            fields.SetField("coUnpaid Income Taxes", "");
            fields.SetField("coChattel Mortgages", "");
            fields.SetField("coLoans on Life Insurance Policies Include Premium Advances", "");
            fields.SetField("coOutstanding Credit Card Debt", "");
            fields.SetField("coOther Debts Schedule G", "");
            fields.SetField("coTOTAL LIABILITIES", "");
            fields.SetField("coNET WORTH", "");
            fields.SetField("COMBINED LIABILITIES", "");
            fields.SetField("Maintenance", "");
            fields.SetField("Apartment Financing", "");
            fields.SetField("Other Mortgages", "");
            fields.SetField("Bank Loans", "");
            fields.SetField("Auto Loans", "");
            fields.SetField("Other_2", "");
            fields.SetField("TOTAL", "");
            fields.SetField("coMaintenance", "");
            fields.SetField("coApartment Financing", "");
            fields.SetField("coOther Mortgages", "");
            fields.SetField("coBank Loans", "");
            fields.SetField("coAuto Loans", "");
            fields.SetField("coOther_2", "");
            fields.SetField("coTOTAL", "");
            fields.SetField("coCOMBINED TOTAL", "");
            fields.SetField("An Endorser or Comaker on Notes", "");
            fields.SetField("Alimony Payments Annual", "");
            fields.SetField("Child Support", "");
            fields.SetField("Legal Action", "");
            fields.SetField("Judgments", "");
            fields.SetField("Bankruptcy", "");
            fields.SetField("Have you ever taken bankruptcy Explain", "");
            fields.SetField("Have you ever taken bankruptcy Explain2", "");
            fields.SetField("Have you ever taken bankruptcy Explain3", "");
            fields.SetField("Applicant or CoApplicantRow1", "");
            fields.SetField("Financial InstitutionRow1", "");
            fields.SetField("Type of AccountRow1", "");
            fields.SetField("Account BalanceRow1", "");
            fields.SetField("Applicant or CoApplicantRow2", "");
            fields.SetField("Financial InstitutionRow2", "");
            fields.SetField("Type of AccountRow2", "");
            fields.SetField("Account BalanceRow2", "");
            fields.SetField("Applicant or CoApplicantRow3", "");
            fields.SetField("Financial InstitutionRow3", "");
            fields.SetField("Type of AccountRow3", "");
            fields.SetField("Account BalanceRow3", "");
            fields.SetField("Applicant or CoApplicantRow4", "");
            fields.SetField("Financial InstitutionRow4", "");
            fields.SetField("Type of AccountRow4", "");
            fields.SetField("Account BalanceRow4", "");
            fields.SetField("Applicant or CoApplicantRow5", "");
            fields.SetField("Financial InstitutionRow5", "");
            fields.SetField("Type of AccountRow5", "");
            fields.SetField("Account BalanceRow5", "");
            fields.SetField("Amount No of SharesRow1", "");
            fields.SetField("DescriptionRow1", "");
            fields.SetField("Marketable ValueRow1", "");
            fields.SetField("NonMarketable ValueRow1", "");
            fields.SetField("Amount No of SharesRow2", "");
            fields.SetField("DescriptionRow2", "");
            fields.SetField("Marketable ValueRow2", "");
            fields.SetField("NonMarketable ValueRow2", "");
            fields.SetField("Amount No of SharesRow3", "");
            fields.SetField("DescriptionRow3", "");
            fields.SetField("Marketable ValueRow3", "");
            fields.SetField("NonMarketable ValueRow3", "");
            fields.SetField("Amount No of SharesRow4", "");
            fields.SetField("DescriptionRow4", "");
            fields.SetField("Marketable ValueRow4", "");
            fields.SetField("NonMarketable ValueRow4", "");
            fields.SetField("Amount No of SharesRow5", "");
            fields.SetField("DescriptionRow5", "");
            fields.SetField("Marketable ValueRow5", "");
            fields.SetField("NonMarketable ValueRow5", "");
            fields.SetField("Description and LocationRow1", "");
            fields.SetField("Date AcquiredRow1", "");
            fields.SetField("CostRow1", "");
            fields.SetField("Actual ValueRow1", "");
            fields.SetField("Mortgage AmountRow1", "");
            fields.SetField("Maturity DateRow1", "");
            fields.SetField("Monthly Operating CostsRow1", "");
            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow1", "");
            fields.SetField("Description and LocationRow2", "");
            fields.SetField("Date AcquiredRow2", "");
            fields.SetField("CostRow2", "");
            fields.SetField("Actual ValueRow2", "");
            fields.SetField("Mortgage AmountRow2", "");
            fields.SetField("Maturity DateRow2", "");
            fields.SetField("Monthly Operating CostsRow2", "");
            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow2", "");
            fields.SetField("Description and LocationRow3", "");
            fields.SetField("Date AcquiredRow3", "");
            fields.SetField("CostRow3", "");
            fields.SetField("Actual ValueRow3", "");
            fields.SetField("Mortgage AmountRow3", "");
            fields.SetField("Maturity DateRow3", "");
            fields.SetField("Monthly Operating CostsRow3", "");
            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow3", "");
            fields.SetField("Description and LocationRow4", "");
            fields.SetField("Date AcquiredRow4", "");
            fields.SetField("CostRow4", "");
            fields.SetField("Actual ValueRow4", "");
            fields.SetField("Mortgage AmountRow4", "");
            fields.SetField("Maturity DateRow4", "");
            fields.SetField("Monthly Operating CostsRow4", "");
            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow4", "");
            fields.SetField("Description and LocationRow5", "");
            fields.SetField("Date AcquiredRow5", "");
            fields.SetField("CostRow5", "");
            fields.SetField("Actual ValueRow5", "");
            fields.SetField("Mortgage AmountRow5", "");
            fields.SetField("Maturity DateRow5", "");
            fields.SetField("Monthly Operating CostsRow5", "");
            fields.SetField("Residential or Commercial If commercial what are the gross rentsRow5", "");
            fields.SetField("DescriptionRow1_2", "");
            fields.SetField("AmountRow1", "");
            fields.SetField("DescriptionRow2_2", "");
            fields.SetField("AmountRow2", "");
            fields.SetField("DescriptionRow3_2", "");
            fields.SetField("AmountRow3", "");
            fields.SetField("DescriptionRow4_2", "");
            fields.SetField("AmountRow4", "");
            fields.SetField("To Whom PayableRow1", "");
            fields.SetField("DateRow1", "");
            fields.SetField("AmountRow1_2", "");
            fields.SetField("DueRow1", "");
            fields.SetField("InterestRow1", "");
            fields.SetField("Pledged as SecurityRow1", "");
            fields.SetField("To Whom PayableRow2", "");
            fields.SetField("DateRow2", "");
            fields.SetField("AmountRow2_2", "");
            fields.SetField("DueRow2", "");
            fields.SetField("InterestRow2", "");
            fields.SetField("Pledged as SecurityRow2", "");
            fields.SetField("To Whom PayableRow3", "");
            fields.SetField("DateRow3", "");
            fields.SetField("AmountRow3_2", "");
            fields.SetField("DueRow3", "");
            fields.SetField("InterestRow3", "");
            fields.SetField("Pledged as SecurityRow3", "");
            fields.SetField("To Whom PayableRow4", "");
            fields.SetField("DateRow4", "");
            fields.SetField("AmountRow4_2", "");
            fields.SetField("DueRow4", "");
            fields.SetField("InterestRow4", "");
            fields.SetField("Pledged as SecurityRow4", "");
            fields.SetField("To Whom PayableRow1_2", "");
            fields.SetField("Mortgage AmountRow1_2", "");
            fields.SetField("Principal RemainingRow1", "");
            fields.SetField("Maturity DateRow1_2", "");
            fields.SetField("To Whom PayableRow2_2", "");
            fields.SetField("Mortgage AmountRow2_2", "");
            fields.SetField("Principal RemainingRow2", "");
            fields.SetField("Maturity DateRow2_2", "");
            fields.SetField("To Whom PayableRow3_2", "");
            fields.SetField("Mortgage AmountRow3_2", "");
            fields.SetField("Principal RemainingRow3", "");
            fields.SetField("Maturity DateRow3_2", "");
            fields.SetField("To Whom PayableRow4_2", "");
            fields.SetField("Mortgage AmountRow4_2", "");
            fields.SetField("Principal RemainingRow4", "");
            fields.SetField("Maturity DateRow4_2", "");
            fields.SetField("DescriptionRow1_3", "");
            fields.SetField("AmountRow1_3", "");
            fields.SetField("DateRow1_2", "");
            fields.SetField("PaymentsRow1", "");
            fields.SetField("SecurityRow1", "");
            fields.SetField("DescriptionRow2_3", "");
            fields.SetField("AmountRow2_3", "");
            fields.SetField("DateRow2_2", "");
            fields.SetField("PaymentsRow2", "");
            fields.SetField("SecurityRow2", "");
            fields.SetField("DescriptionRow3_3", "");
            fields.SetField("AmountRow3_3", "");
            fields.SetField("DateRow3_2", "");
            fields.SetField("PaymentsRow3", "");
            fields.SetField("SecurityRow3", "");
            fields.SetField("DescriptionRow4_3", "");
            fields.SetField("AmountRow4_3", "");
            fields.SetField("DateRow4_2", "");
            fields.SetField("PaymentsRow4", "");
            fields.SetField("SecurityRow4", "");
            fields.SetField("SourceRow1", "");
            fields.SetField("Amount Last YearRow1", "");
            fields.SetField("Is this recurringRow1", "");
            fields.SetField("SourceRow2", "");
            fields.SetField("Amount Last YearRow2", "");
            fields.SetField("Is this recurringRow2", "");
            fields.SetField("SourceRow3", "");
            fields.SetField("Amount Last YearRow3", "");
            fields.SetField("Is this recurringRow3", "");
            fields.SetField("SourceRow4", "");
            fields.SetField("Amount Last YearRow4", "");
            fields.SetField("Is this recurringRow4", "");
            fields.SetField("DividendApp1", "");
            fields.SetField("DividendCo1", "");
            fields.SetField("DividendApp2", "");
            fields.SetField("DividendCo2", "");
            fields.SetField("DividendApp3", "");
            fields.SetField("DividendCo3", "");
            fields.SetField("Day", "");
            fields.SetField("Month", "");
            fields.SetField("Year", "");
            fields.SetField("CoApp Date", "");
            fields.SetField("App DOB", "");
            fields.SetField("App SSN", "");
            fields.SetField("Applicant Address", "");
            fields.SetField("Applicant City", "");
            fields.SetField("Applicant State", "");
            fields.SetField("Applicant Zip", "");
            fields.SetField("CoApp DOB", "");
            fields.SetField("CoApp SSN", "");
            fields.SetField("CoApp Address", "");
            fields.SetField("CoApp City", "");
            fields.SetField("CoApp State", "");
            fields.SetField("CoApp Zip", "");
            fields.SetField("Other Adult Name", "");
            fields.SetField("Other DOB", "");
            fields.SetField("Other SSN", "");
            fields.SetField("Other Address", "");
            fields.SetField("Other City", "");
            fields.SetField("Other State", "");
            fields.SetField("Other Zip", "");
            fields.SetField("Fowarding Address 1", "");
            fields.SetField("Forwarding Address 2", "");
            fields.SetField("Onwer Biz Address 1", "");
            fields.SetField("Owner Biz Address 2", "");
            fields.SetField("Unit Owner Day Phone", "");
            fields.SetField("Unit Owner Eve Phone", "");
            fields.SetField("Unit Owner Cell Phone", "");
            fields.SetField("Unit Owner Email", "");
            fields.SetField("Applicant Email", "");
            fields.SetField("Applicant Employer", "");
            fields.SetField("Applicant Business Email", "");
            fields.SetField("Applicant Empl Address", "");
            fields.SetField("Applicant Cell Phone", "");
            fields.SetField("Applicant Empl Address 2", "");
            fields.SetField("Applicant Work Phone", "");
            fields.SetField("Other Contact Information", "");
            fields.SetField("CoApp Email", "");
            fields.SetField("CoApp Employer", "");
            fields.SetField("CoApp Business Email", "");
            fields.SetField("CoApp Empl Address", "");
            fields.SetField("CoApp Cell Phone", "");
            fields.SetField("CoApp Empl Address 2", "");
            fields.SetField("CoApp Work Phone", "");
            fields.SetField("CoApp Other Contact Information", "");
            fields.SetField("Emergency Contact", "");
            fields.SetField("Relationship", "");
            fields.SetField("Emergency Email", "");
            fields.SetField("Emergency Contact Home Phone", "");
            fields.SetField("Emergency contact Cell Phone", "");
            fields.SetField("Additional Occupant 1", "");
            fields.SetField("Age 1", "");
            fields.SetField("Relationship 1", "");
            fields.SetField("Additional Occupant 2", "");
            fields.SetField("Age 2", "");
            fields.SetField("Relationship 2", "");
            fields.SetField("Additional Occupant 3", "");
            fields.SetField("Age 3", "");
            fields.SetField("Relationship 3", "");
            fields.SetField("Additional Occupant 4", "");
            fields.SetField("Age 4", "");
            fields.SetField("Relationship 4", "");
            fields.SetField("Additional Occupant 5", "");
            fields.SetField("Age 5", "");
            fields.SetField("Relationship 5", "");
            fields.SetField("Other Date", "");
            fields.SetField("Guarantor Name", "");
            fields.SetField("Guarantor Date", "");
            fields.SetField("Gurantor Date", "");
            fields.SetField("Check Box6", "");
            fields.SetField("Check Box7", "");
            fields.SetField("Check Box8", "");
            fields.SetField("Check Box9", "");
            fields.SetField("Check Box10", "");
            fields.SetField("Check Box11", "");
            fields.SetField("Check Box12", "");
            fields.SetField("Text26", "");
            fields.SetField("Text28", "");
            fields.SetField("Text29", "");
            fields.SetField("Text30", "");
            fields.SetField("Name of Corporation 1", "");
            fields.SetField("Name of Corporation 2", "");
            fields.SetField("Occupant 1", "");
            fields.SetField("Occupant 3", "");
            fields.SetField("Occupant 5", "");
            fields.SetField("Occupant 7", "");
            fields.SetField("Occupant 2", "");
            fields.SetField("Occupant 4", "");
            fields.SetField("Occupant 6", "");
            fields.SetField("Occupant 8", "");
            fields.SetField("Term of Occupancy", "");
            fields.SetField("Relationship to Corporation", "");
            fields.SetField("Name  Title of Authorized Officer", "");
            fields.SetField("Date_19", "");
            fields.SetField("existence or nonexistence of a Sprinkler System in the Leased Premises 1", "");
            fields.SetField("existence or nonexistence of a Sprinkler System in the Leased Premises 2", "");
            fields.SetField("1", "");
            fields.SetField("2", "");
            fields.SetField("the Leased", "");
            fields.SetField("undefined", "");
            fields.SetField("inspected was on", "");
            fields.SetField("Acknowledgment  Signatures", "");
            fields.SetField("New York State Real Property Law Article 7 Section 231a 1", "");
            fields.SetField("New York State Real Property Law Article 7 Section 231a 2", "");
            fields.SetField("1_2", "");
            fields.SetField("2_2", "");
            fields.SetField("1_3", "");
            fields.SetField("2_3", "");
            fields.SetField("Date", "");
            fields.SetField("Date_2", "");
            fields.SetField("Date_3", "");
            fields.SetField("Check Box1", "");
            fields.SetField("Check Box2", "");

            stamper.FormFlattening = true;
            stamper.Dispose();

            var result = stream.ToArray();

            reader.Close();

            return result;
        }
    }
}
