//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_RealtorEmployments
    {
        public int Id { get; set; }
        public string LabelName { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> OccupationId { get; set; }
        public Nullable<int> SalaryId { get; set; }
        public Nullable<int> ReferenceId { get; set; }
    
        public virtual db_RealtorClients db_RealtorClients { get; set; }
        public virtual db_UserAddresses db_UserAddresses { get; set; }
        public virtual db_UserOccupations db_UserOccupations { get; set; }
        public virtual db_UserSalaries db_UserSalaries { get; set; }
        public virtual db_UserReferences db_UserReferences { get; set; }
    }
}
