//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_RealtorClients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_RealtorClients()
        {
            this.db_RealtorBanks = new HashSet<db_RealtorBanks>();
            this.db_RealtorEmployments = new HashSet<db_RealtorEmployments>();
            this.db_RealtorHomes = new HashSet<db_RealtorHomes>();
            this.db_RealtorReferences = new HashSet<db_RealtorReferences>();
            this.db_UserLandlords = new HashSet<db_UserLandlords>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string LabelName { get; set; }
        public int ClientUserId { get; set; }
        public Nullable<int> ContactId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorBanks> db_RealtorBanks { get; set; }
        public virtual db_UserContacts db_UserContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorEmployments> db_RealtorEmployments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorHomes> db_RealtorHomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorReferences> db_RealtorReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_UserLandlords> db_UserLandlords { get; set; }
    }
}
