//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_RealtorHomes
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string LabelName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> LeaseId { get; set; }
        public Nullable<int> LandlordId { get; set; }
    
        public virtual db_RealtorClients db_RealtorClients { get; set; }
        public virtual db_UserAddresses db_UserAddresses { get; set; }
        public virtual db_UserLandlords db_UserLandlords { get; set; }
        public virtual db_UserLeases db_UserLeases { get; set; }
    }
}
