//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_UserLandlords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_UserLandlords()
        {
            this.db_RealtorHomes = new HashSet<db_RealtorHomes>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string LabelName { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<int> AddressId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual db_RealtorClients db_RealtorClients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorHomes> db_RealtorHomes { get; set; }
        public virtual db_UserAddresses db_UserAddresses { get; set; }
        public virtual db_UserAddresses db_UserAddresses1 { get; set; }
        public virtual db_UserContacts db_UserContacts { get; set; }
    }
}
