//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_UserAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_UserAccounts()
        {
            this.db_RealtorBanks = new HashSet<db_RealtorBanks>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string LabelName { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Number { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorBanks> db_RealtorBanks { get; set; }
    }
}
