//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_UserSalaries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public db_UserSalaries()
        {
            this.db_RealtorEmployments = new HashSet<db_RealtorEmployments>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string LabelName { get; set; }
        public Nullable<decimal> AnnualSalary { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> OtherIncomeSource { get; set; }
        public Nullable<decimal> OtherIncomeAmount { get; set; }
        public Nullable<decimal> TotalAnnualIncome { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_RealtorEmployments> db_RealtorEmployments { get; set; }
    }
}
