//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicaitonGeneration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationEntities : DbContext
    {
        public ApplicationEntities()
            : base("name=ApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<db_RealtorBanks> db_RealtorBanks { get; set; }
        public virtual DbSet<db_RealtorClients> db_RealtorClients { get; set; }
        public virtual DbSet<db_RealtorEmployments> db_RealtorEmployments { get; set; }
        public virtual DbSet<db_RealtorHomes> db_RealtorHomes { get; set; }
        public virtual DbSet<db_RealtorReferences> db_RealtorReferences { get; set; }
        public virtual DbSet<db_UserAccounts> db_UserAccounts { get; set; }
        public virtual DbSet<db_UserAddresses> db_UserAddresses { get; set; }
        public virtual DbSet<db_UserContacts> db_UserContacts { get; set; }
        public virtual DbSet<db_UserLandlords> db_UserLandlords { get; set; }
        public virtual DbSet<db_UserLeases> db_UserLeases { get; set; }
        public virtual DbSet<db_UserOccupations> db_UserOccupations { get; set; }
        public virtual DbSet<db_UserReferences> db_UserReferences { get; set; }
        public virtual DbSet<db_UserSalaries> db_UserSalaries { get; set; }
    }
}
