//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationGeneration
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb_SurveyAnswers
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> BeaconId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string SurveyAnswer { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
    
        public virtual rb_Companies rb_Companies { get; set; }
        public virtual rb_SurveyBeacons rb_SurveyBeacons { get; set; }
        public virtual rb_SurveyQuestions rb_SurveyQuestions { get; set; }
    }
}
